kafka-streams-service:
  custom-audience: kafka-streams-service

server:
  port: 8187
  servlet:
    context-path: /kafka-streams-service

# To protect this service with keycloak
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9091/auth/realms/microservices-realm
          jwk-set-uri: http://localhost:9091/auth/realms/microservices-realm/protocol/openid-connect/certs

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

security:
  paths-to-ignore: /api-docs

# Usaremos o cliente admin kafka onde precisamos repetir a configuração e nós
retry-config:
  initial-interval-ms: 1000
  max-interval-ms: 10000
  multiplier: 2.0
  maxAttempts: 3
  sleep-time-ms: 2000

# Obter servidores de bootstrap e informações do servidor de esquema
kafka-config:
  bootstrap-servers: localhost:19092, localhost:29092, localhost:39092
  schema-registry-url-key: schema.registry.url
  schema-registry-url: http://localhost:8081
  topic-names-to-create:
    - twitter-topic
    - twitter-analytics-topic

kafka-streams-config:
  application-id: kafka-streams-application
  # nomes de tópicos de entrada
  input-topic-name: twitter-topic
  # nomes de tópicos de saída
  output-topic-name: twitter-analytics-topic
  # Local de arquivo de estado e nome de armazenamento para armazenar o estado de computação que fizermos e usá-lo
  # para retornar um endpoint.
  state-file-location: ${HOME}/kafka-streaming-state
  word-count-store-name: word-count-store