elastic-query-web-client:
  webclient:
    connect-timeout-ms: 10000  # Tempo limite de conexão
    read-timeout-ms: 10000     # Tempo limite de leitura
    write-timeout-ms: 10000    # Tempo limite de escrita
    max-in-memory-size: 10485760 # 10MB  Tamanho máximo de memória que o cliente pode utilizar
    content-type: 'application/json'  # Conteúdo padrão
    accept-type: 'text/event-stream'
    base-url: 'http://localhost:8183/reactive-elastic-query-service/documents'
  query-by-text:
    method: POST
    uri: "/get-doc-by-text"
    accept: ${elastic-query-web-client.webclient.accept-type}

server:
  port: 8184

spring:
  webflux:
    base-path: /reactive-elastic-query-web-client
  thymeleaf:
    # Definido como false para permitir que os modelos thymeleaf sejam carregados quando
    # eles são alterados durante o desenvolvimento
    cache: false
    reactive:
      max-chunk-size: 8192  # Tamanho máximo do pedaço (chunk) reativo do thymeleaf
  codec:
    max-in-memory-size: 25MB  # tamanho máximo da memória