elastic-query-service:
  version: v1

server:
  port: 8183
  servlet:
    # Propriedade necessária para definir um caminho de contexto para um aplicativo da web
    context-path: /elastic-query-service

# Estas propriedades serão lidas pela classe ElasticQueryConfigData do módulo: app-config-data
elastic-query-config:
  text-field: text  # propriedade da classe TwitterIndexModel do módulo: elastic-model

# Estas propriedades serão lidas pela classe ElasticConfigData no módulo: app-config-data
elastic-config:
  index-name: twitter-index
  connection-url: http://localhost:9200
  connect-timeout-ms: 5000
  socket-timeout-ms: 30000

# Estas propriedades serão lidas pela classe WebSecurityConfig no módulo: elastic-query-service
user-config:
  username: test
#  password: '{cipher}baeb90d57edb9a050b97b98a7d8cabe80ee884e6fff16c22956172459a43e54d'
  password: '{cipher}78620071212faa6fbc1331721ce51e9afd65baf413eaf4cb8c3560831e1f1118'
  roles: USER

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

# Estas propriedades serão lidas pela classe WebSecurityConfig no módulo: elastic-query-service
security:
  paths-to-ignore: /api-docs