server:
  port: 8181

# Coloca-se aqui todas as configurações que estavam no application.yml do módulo twitter-to-kafka-service e
#  apaga-se o conteúdo do application.yml do módulo twitter-to-kafka-service
twitter-to-kafka-service:
  twitter-keywords:  # Buscando no Twitter tweets com estas palavras
    - Java
    - Microservices
    - Kafka
    - Elasticsearch
  welcome-message: Hello microservices!
  enable-mock-tweets: true  # Irá executar o Twitter Mockado
  mock-min-tweet-length: 5
  mock-max-tweet-length: 15
  mock-sleep-ms: 10000

retry-config:
  initial-interval-ms: 1000
  max-interval-ms: 10000
  multiplier: 2.0
  maxAttempts: 3
  sleep-time-ms: 2000

# Configuração do kafka
kafka-config:
  # host:port  As mesmas configurações do docker-compose file
  bootstrap-servers: localhost:19092, localhost:29092, localhost:39092
  # As mesmas configurações do docker-compose file
  schema-registry-url-key: schema.registry.url
  # As mesmas configurações do docker-compose file
  schema-registry-url: http://localhost:8081
  topic-name: twitter-topic
  topic-names-to-create:
    - twitter-topic
  num-of-partitions: 3
  replication-factor: 3

kafka-producer-config:
  # Como iremos ler os dados do topic kafka no producer
  key-serializer-class: org.apache.kafka.common.serialization.LongSerializer  # Para ler a chave que é Tipo Long
  value-serializer-class: io.confluent.kafka.serializers.KafkaAvroSerializer  # Para ler o valor que é Tipo Avro, mesmo do consumer
  compression-type: snappy  # Options: gzip, none, lz4 and snappy ( esta é do google)
  # Options: 0, 1, all
  # 0 -> não aguardará e retornará imediatamente sem confirmação,
  # 1 -> aguardará apenas o corretor (broker) que recebe as solicitações do cliente produtor (producer),
  # all -> Todos
  acks: all  # Reconhecimentos -> Todos, para obter reconhecimentos de todas as réplicas para ser mais resiliente.
  batch-size: 16384  # Tamanho padrão do Lote
  batch-size-boost-factor: 100  # Podemos alterar para ver se tem um melhor desempenho
  linger-ms: 5  # 5 milissegundos Add a delay on producer in case of light load
  request-timeout-ms: 60000  # Tempo limite de solicitação 60 segundos
  retry-count: 5  # Quantidade de repetições (novas tentativas) em caso de erro
